# action.yml
name: "Runme Action"
description: "A GitHub Action to run Runme in CI."
author: Stateful Inc.
branding:
  icon: play
  color: purple
inputs:
  parallel:
    description: If set to true, Runme will run these commands in parallel.
    default: "false"
  workflows:
    description: Only use if `command` parameter is set to `run` or `exec`. Name of the markdown code cell to run or a list of code cells to execute in order.
    required: false
  version:
    description: Defines which Runme version to use. You can find all Runme release on [GitHub](https://github.com/stateful/runme/releases).
    required: false
  project:
    description: Path to project directory (enables project mode)
    default: ${{ github.workspace }}
  serverAddress:
    description: If serverAddress is set the action will start a Runme server on given address.
    required: false
  token:
    description: 'A Github token to download the Runme release without being rate limited. Defaults to token of workflow initiator.'
    required: false
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
